#!/bin/bash

# Clean coded data
rm -r Coded
mkdir Coded
rm _Codificador/*.coded >/dev/null 2>&1

# MAKE codificador
clear
echo "\n############### MAKE Codificador ################\n"
cd _Codificador/
make clean-all
make params
make all


# Run codvector
echo "\n############### RUN Codvector ################\n"
sh codvector.sh $1

echo "\n\n############################################################"
echo "################## OUTPUT match verifier ###################"
echo "############################################################"
cd ../OutputVerifier/
sh verifier.sh $1
echo "############################################################\n"


# Clean .o files
cd ../_Codificador/
make cleano >/dev/null 2>&1

# Clean coded data
cd ..
rm -r Coded
rm _Codificador/*.coded >/dev/null 2>&1



# Create tree output
tree -o tree.out


