#!/bin/bash

# Clean coded data and create dirs
rm -r Coded >/dev/null 2>&1
mkdir Coded
rm _Codificador/*.coded >/dev/null 2>&1
mkdir Decoded >/dev/null 2>&1

# MAKE codificador
clear
echo -e "\n############### MAKE Codificador ################\n"
cd _Codificador/
make clean
make

# Run codvector
echo -e "\n############### RUN Codvector ################\n"
sh codvector.sh $1

echo -e "\n\n############################################################"
echo "################## OUTPUT match verifier ###################"
echo "############################################################"
cd ../OutputVerifier/
sh verifier.sh $1
echo -e "############################################################\n"


# generates the image
cd ../_Descodificador
make >/dev/null 2>&1
./decvector.sh $1 >/dev/null 2>&1
