.TH "cmdline_parser_params" 3 "Fri Nov 25 2011" "Version v1.0.0" "Cuda Codificador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cmdline_parser_params \- 
.PP
The additional parameters to pass to parser functions.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <params.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBoverride\fP"
.br
.RI "\fIwhether to override possibly already present options (default 0) \fP"
.ti -1c
.RI "int \fBinitialize\fP"
.br
.RI "\fIwhether to initialize the option structure \fBgengetopt_args_info\fP (default 1) \fP"
.ti -1c
.RI "int \fBcheck_required\fP"
.br
.RI "\fIwhether to check that all required options were provided (default 1) \fP"
.ti -1c
.RI "int \fBcheck_ambiguity\fP"
.br
.RI "\fIwhether to check for options already specified in the option structure \fBgengetopt_args_info\fP (default 0) \fP"
.ti -1c
.RI "int \fBprint_errors\fP"
.br
.RI "\fIwhether getopt_long should print an error message for a bad option (default 1) \fP"
.in -1c
.SH "Detailed Description"
.PP 
The additional parameters to pass to parser functions. 
.SH "Field Documentation"
.PP 
.SS "int \fBcheck_ambiguity\fP"
.PP
whether to check for options already specified in the option structure \fBgengetopt_args_info\fP (default 0) 
.SS "int \fBcheck_required\fP"
.PP
whether to check that all required options were provided (default 1) 
.SS "int \fBinitialize\fP"
.PP
whether to initialize the option structure \fBgengetopt_args_info\fP (default 1) 
.SS "int \fBoverride\fP"
.PP
whether to override possibly already present options (default 0) 
.SS "int \fBprint_errors\fP"
.PP
whether getopt_long should print an error message for a bad option (default 1) 

.SH "Author"
.PP 
Generated automatically by Doxygen for Cuda Codificador from the source code.
