.TH "deprecated" 3 "Fri Nov 25 2011" "Version v1.0.0" "Cuda Codificador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
 
.IP "\fBGlobal \fBcmdline_parser2\fP(int argc, char **argv, struct \fBgengetopt_args_info\fP *args_info, int override, int initialize, int check_required) \fP" 1c
use \fBcmdline_parser_ext()\fP instead 
.PP
.PP
 
.IP "\fBGlobal \fBcmdline_parser_configfile\fP(const char *filename, struct \fBgengetopt_args_info\fP *args_info, int override, int initialize, int check_required) \fP" 1c
use \fBcmdline_parser_config_file()\fP instead 
.PP

