.TH "line_list" 3 "Fri Nov 25 2011" "Version v1.0.0" "Cuda Codificador" \" -*- nroff -*-
.ad l
.nh
.SH NAME
line_list \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "char * \fBstring_arg\fP"
.br
.ti -1c
.RI "struct \fBline_list\fP * \fBnext\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBline_list\fP* \fBnext\fP"
.SS "char* \fBstring_arg\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Cuda Codificador from the source code.
